# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 341531cdd55ced56cfbe7743501498dcd35a7806f5ad63c18f812d95d5bcdbf279a8f5c744bd1c4fea8a1b8aca269571c1192f16481fac236e96b240a3859ad8

test:
  secret_key_base: 65f4701b140fd8c6c0fdd4a0b85b171235337b9ea46330e656bd9173cea317cdb55ebf0b913de4005f57131a6eb92f9e6186a83c8617e043429d176bfcb050a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
